# Add the image for this app & mongodb as services.
version: "3"

services:
  mongo:
    image: mongo:4.0.10
    container_name: mongo-db
    volumes:
      - ./data:/data/db
    restart: unless-stopped
  app:
    image: jcedeno/stclock:latest
    container_name: stclock-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/stclock
    restart: unless-stopped